site_name: MkDocs Template
site_description: "This is a template repository for documentation, wiki, knowledge base and technical blog using 'Material for MkDocs'."
site_url: https://mkdocs.bybatkhuu.dev
repo_name: bybatkhuu/docs.mkdocs-template
repo_url: https://github.com/bybatkhuu/docs.mkdocs-template
theme:
  name: material
  # name: readthedocs
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    # logo: fontawesome/brands/python
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      accent: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - tags
  - meta
  - mkdocstrings
  - awesome-nav
  # - literate-nav
  - blog:
      blog_dir: blog
      post_date_format: medium
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
      blog_toc: true
extra:
  version:
    provider: mike
