site_name: MkDocs Template
site_description: "This is a template repository for documentation, wiki, knowledge base and technical blog using 'Material for MkDocs'."
site_url: https://mkdocs.bybatkhuu.dev
repo_name: bybatkhuu/docs.mkdocs-template
repo_url: https://github.com/bybatkhuu/docs.mkdocs-template
theme:
  name: material
  # name: readthedocs
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    # logo: fontawesome/brands/python
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    # - navigation.instant
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      accent: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - assets/js/mathjax.js
  - assets/js/tex-mml-chtml.js
plugins:
  - meta
  - tags
  - search
  - awesome-nav
  - mkdocstrings
  - blog:
      # post_excerpt: required
      post_excerpt_max_authors: 3
      post_date_format: medium
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
      blog_toc: true
      draft: true
      draft_if_future_date: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      # categories_allowed:
      #   - Python
      #   - Data Science
      #   - Machine Learning
      #   - AI/DL
      #   - DevOps
      #   - Cloud
      #   - Tools
      #   - Tutorials
      #   - Tips
      #   - Examples
      #   - Others
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bybatkhuu
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/bybatkhuu
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/bybatkhuu
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/bybatkhuu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bybatkhuu
copyright: Copyright &copy; 2025 - Batkhuu Byambajav
