authors:
  {{cookiecutter.author_username}}:
    name: {{cookiecutter.author_fullname}}
    description: Creator, maintainer
    # avatar: https://avatars.githubusercontent.com/u/AVATAR_ID
    url: https://github.com/{{cookiecutter.author_username}}
